# 高度多样性测试配置 - 专门测试3D路径规划
# 使用方法: export CONFIG_FILE_PATH=configs/params_altitude_test.yaml && python main.py

environment:
  num_envs: 2
  seed: 3
  x_dim: 50
  y_dim: 50

sensor:
  type: "rgb_camera"
  field_of_view:
    angle_x: 60
    angle_y: 60
  pixel:
    number_x: 57
    number_y: 57
  encoding: "rgb8"
  model:
    type: "altitude_dependent"  # 高度依赖的传感器模型
    coeff_a: 0.05
    coeff_b: 0.2
  simulation:
    type: "random_field"
    cluster_radius: 5

mapping:
  prior: 0.5

experiment:
  title: "altitude_diversity_test"
  constraints:
    spacing: 5
    min_altitude: 5
    max_altitude: 15        # 3个高度层: 5, 10, 15
    budget: 8
    num_actions: 6          # 6动作空间: 包含上升/下降
  uav:
    max_v: 5
    max_a: 2
    sampling_time: 2
    communication_range: 25
    fix_range: True
    failure_rate: 0
  missions:
    type: "COMA"
    mission_mode: "training"
    n_episodes: 500
    patience: 100
    n_agents: 4
    action_space: "larger"
    planning_uncertainty: "SE"
    eps_max: 0.5
    eps_min: 0.02
    eps_anneal_phase: 10000
    use_eps: True
    class_weighting: [0, 1]
    reward_normalization: false
  coverage_weight: 0.15
  distance_weight: 0.0
  footprint_weight: 0.5
  collision_weight: 2.0
  collision_distance: 5.0
  altitude_diversity_weight: 0.5  # ⭐ 高度多样性奖励权重

evaluation:
  repetitions: 1
  metrics:
    - "num_waypoints"
    - "paths"
    - "rmse"
    - "wrmse"
    - "mll"
    - "wmll"
    - "run_time"

networks:
  device: "cuda"
  type: "CNN"
  data_passes: 2
  batch_size: 32
  batch_number: 2
  copy_rate: 10
  gamma: 0.99
  lambda: 0.8
  actor:
    hidden_dim: 128
    learning_rate: 0.00001
    momentum: 0.9
    gradient_norm: 10
  critic:
    target_update_mode: "hard"
    tau: 0.01
    update_mode: "random_batches"
    synchronization: "no"
    fc1_dim: 64
    learning_rate: 0.0001
    momentum: 0.9
    gradient_norm: 10

classification:
  n_episodes: 300
  data_split: [0.4, 0.4, 0.2]
  number_epochs: 100
  batch_size: 50

# 配置说明:
# ⭐ altitude_diversity_weight: 0.5
#   - 鼓励agents在不同高度探索
#   - 奖励空间多样性(agents分布在不同高度层)
#   - 奖励时间变化(agents垂直移动)
#
# 预期效果:
# - 航线会在5m, 10m, 15m之间变化
# - agents不会全部停留在同一高度
# - 高度标准差应该 > 2.0
# - 每个episode应有15-25%的步骤包含高度变化
#
# 对比实验:
# - 设置 altitude_diversity_weight: 0.0 运行基线实验
# - 对比高度分布和路径效率的差异
