environment:
  seed: 3  # not 0, would mean same start position for every uav
  x_dim: 50 # [m]
  y_dim: 50 # [m]

sensor:
  type: "rgb_camera"
  field_of_view:
    angle_x: 60 # [°]
    angle_y: 60 # [°]
  pixel:
    number_x: 57 # --> 10cm resolution
    number_y: 57
  encoding: "rgb8"
  model:
    type: "altitude_dependent"
    coeff_a: 0.05
    coeff_b: 0.2

mapping:
  prior: 0.5
  simulation:
    type: "random_field"
    cluster_radius: 5 # [m]

MARL_cast:
  state_space:
    spacing: 5 # [m]
    min_altitude: 5 # [m]
    max_altitude: 15 # [m]
    budget: 14 # [s]
    random_start: True
  action_space:
    num_actions: 6
  reward:
    reward_normalization: false
  communication:
    communication_range: 25  # [m]
    fix_range: True
    failure_rate: 0

mission:
  type: "COMA"              # COMA, DeepQ, or CentralQV
  mission_mode: "training"     # training or deployment
  n_episodes: 1500   # full batch fillings
  patience: 100
  n_agents: 4
  eval_frequency: 50

exploration:
  use_eps: True
  eps_max: 0.5
  eps_min: 0.02
  eps_anneal_phase: 10000

adaptive_planning:
  class_weighting: [0, 1]
  planning_uncertainty: "SE"         # SE, RMSE or MAE

baselines:
  lawn_mower:
    trials: 50
    altitude: 5
  random:
    n_episodes: 50
  information_gain:
    trials: 1
    communication: true

networks:
  actor:
    hidden_dim: 128
    learning_rate: 0.00001
    momentum: 0.9
    gradient_norm: 10
  critic:
    target_update_mode: "hard"
    tau: 0.01
    synchronization: "no"
    fc1_dim: 64
    learning_rate: 0.0001
    momentum: 0.9
    gradient_norm: 10
  updates:
    data_passes: 5
    batch_size: 600
    batch_number: 5
    copy_rate: 10     # full episodes
    shuffle_batches: true

rl_hyperparams:
  gamma: 0.99
  lambda: 0.8

