# 中等训练配置 - 平衡速度和效果
# 推荐用于实际训练

environment:
  num_envs: 2
  seed: 3
  x_dim: 50
  y_dim: 50

sensor:
  type: "rgb_camera"
  field_of_view:
    angle_x: 60
    angle_y: 60
  pixel:
    number_x: 57
    number_y: 57
  encoding: "rgb8"
  model:
    type: "altitude_dependent"
    coeff_a: 0.05
    coeff_b: 0.2
  simulation:
    type: "random_field"
    cluster_radius: 5

mapping:
  prior: 0.5

experiment:
  title: "balanced_training"
  constraints:
    spacing: 5
    min_altitude: 5
    max_altitude: 15
    budget: 12               # ← 折中方案：比14短但比8长
    num_actions: 6
  uav:
    max_v: 5
    max_a: 2
    sampling_time: 2
    communication_range: 25
    fix_range: True
    failure_rate: 0
  missions:
    type: "COMA"
    mission_mode: "training"
    n_episodes: 1000         # ← 充分但不过度
    patience: 100
    n_agents: 4
    action_space: "larger"
    planning_uncertainty: "SE"
    eps_max: 0.5
    eps_min: 0.02
    eps_anneal_phase: 10000
    use_eps: True
    class_weighting: [0, 1]
    reward_normalization: false
  coverage_weight: 0.15
  distance_weight: 0.0
  footprint_weight: 0.5
  collision_weight: 2.0
  collision_distance: 5.0
  baselines:
    lawnmower:
      trials: 50
      altitude: 5
    random:
      n_episodes: 50
    information_gain:
      trials: 50
      communication: true

evaluation:
  repetitions: 1
  metrics:
    - "num_waypoints"
    - "paths"
    - "rmse"
    - "wrmse"
    - "mll"
    - "wmll"
    - "run_time"

networks:
  device: "cuda"
  type: "CNN"
  data_passes: 3           # ← 保持较好的样本利用
  batch_size: 48           # ← 折中大小
  batch_number: 3          # ← 保持原值
  copy_rate: 10
  gamma: 0.99
  lambda: 0.8
  actor:
    hidden_dim: 128
    learning_rate: 0.00001
    momentum: 0.9
    gradient_norm: 10
  critic:
    target_update_mode: "hard"
    tau: 0.01
    update_mode: "random_batches"
    synchronization: "no"
    fc1_dim: 64
    learning_rate: 0.0001
    momentum: 0.9
    gradient_norm: 10

classification:
  n_episodes: 300
  data_split: [0.4, 0.4, 0.2]
  number_epochs: 100
  batch_size: 50

# 配置说明:
# - budget: 12 (减少CPU压力，但保持足够的航线长度)
# - n_episodes: 1000 (充分训练但不过度)
# - batch_size: 48 (平衡计算速度和训练稳定性)
#
# 预期效果:
# - 总训练步数: ~3,333步
# - 预计时间: 20-30小时
# - 模型性能: 接近完整配置的95%
# - 可部署使用
